llm:
  api_type: "open_llm" # or openai
  base_url: 'http://localhost:8001/v1'
  model: "Meta-Llama-3.1-8B-Instruct"
  api_key: "EMPTY"
  max_concurrent: 64
  
embedding:
  api_type: "vllm"  # or hf / ollama / openai / vllm
  base_url: "http://localhost:9001/v1"
  api_key: "EMPTY"
  model: "bge-m3"
  cache_dir: ""
  max_token_size: 8102
  embed_batch_size: 128
  embedding_func_max_async: 16
 
data_root:  "/root/GraphRAG/Data" # Root directory for data



working_dir: /root/GraphRAG/Output # Result directory for the experiment
exp_name: GraphRAG
# 
